### PR TITLE
Bump ember-power-select

### PR DESCRIPTION
**Pull request by erikap**
Bump ember-power-select to improve compatibility with embroider

### CODE REVIEW

**Review by Windvis — APPROVED** [review]

**Review by Windvis — COMMENTED** [review]
It seems the lock file changes aren't included in this PR :smile:

**Comment by erikap** [comment]
Updated package-lock.json but CI is failing now. Not sure how to fix this @Windvis

**Comment by erikap** [comment]
Lock file was generated with npm v8.3.0

**Comment by Windvis** [comment]
https://github.com/appuniversum/ember-appuniversum/pull/203 I rolled back to a lock file generated with npm 6 and that seems to get past the installation job. So I'm afraid we'll need to reroll this one with npm 6 as well. Not sure if we should update the CI setup to use node 16 + npm 8 already. I usually try to stick with the "supported" version in the readme, but we might be able to get away with it here since we control the consuming apps as well.

**Comment by Windvis** [comment]
That PR has been merged, could you try rebasing and using npm 6 instead? I would do it, but I can't push to your repo :smile:.

**Comment by erikap** [comment]
Seems to have worked @Windvis :ok_hand:

**Pull request merged**
